### ISSUE TITLE
ImagePicker.pickImage(source: ImageSource.gallery) 没反应

### ISSUE THREAD

**Issue by yrom** [simplezhli/flutter_deer#24]
### 运行环境 ###

- [x] 设备型号：华为 p30 pro
- [x] 设备系统版本：9
- [x] Flutter 版本：1.7.8 hotfix3

### 具体问题描述 ###
1. 登录完成
2. 填店铺资料页，点“选执照”的按钮
3. 通过授权
4. 没有调出相册
5. 再次点击按钮有异常如下：

```
E/flutter (28517): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null)
E/flutter (28517): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (28517): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (28517): <asynchronous suspension>
E/flutter (28517): #2      ImagePicker.pickImage (package:image_picker/image_picker.dart:53:40)
E/flutter (28517): <asynchronous suspension>
E/flutter (28517): #3      _StoreAuditState._getImage.<anonymous closure> (package:flutter_deer/store/store_audit_page.dart:34:32)
E/flutter (28517): #4      State.setState (package:flutter/src/widgets/framework.dart:1141:30)
E/flutter (28517): #5      _StoreAuditState._getImage (package:flutter_deer/store/store_audit_page.dart:33:5)
E/flutter (28517): #6      _StoreAuditState._buildBody.<anonymous closure> (package:flutter_deer/store/store_audit_page.dart:117:21)
E/flutter (28517): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter (28517): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter (28517): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (28517): #10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (28517): #11     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter (28517): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter (28517): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter (28517): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter (28517): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (28517): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (28517): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (28517): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (28517): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (28517): #20     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (28517): #21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (28517): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (28517): #23     _invoke1 (dart:ui/hooks.dart:250:10)
E/flutter (28517): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
E/flutter (28517): 
```

**Comment by simplezhli** [comment]
首先尝试一下正式包有没有问题：https://www.pgyer.com/gYXj

如果没有问题，尝试删除build文件，重新安装看问题是否复现。

**Comment by simplezhli** [comment]
问题找到了，是我写的高德地图插件的权限处理影响了image_picker的权限回调。你可以拉取最新代码，`packages upgrade`更新最新的地图插件就好了。
